workspace:
  base: /go
  path: src/github.com/skuid/keyman

pipeline:
  test:
    image: golang:1.9-alpine
    commands:
      - go build -i
      - go test -v ./...
      - go vet ./...

  test_race:
    image: golang:1.9
    commands:
      - go test -race ./...

  build-image:
    image: quay.io/skuid/docker-builder:17.06.0-ce
    environment:
      - DOCKER_HOST=tcp://build2.skuid.ink:2375
    commands:
      - docker build --build-arg COMMIT_SHA=${DRONE_COMMIT_SHA} -t quay.io/skuid/keyman:${DRONE_BRANCH}-${DRONE_BUILD_NUMBER} .
    when:
      event: push

  publish:
    image: quay.io/skuid/docker-builder:17.06.0-ce
    environment:
      - DOCKER_HOST=tcp://build2.skuid.ink:2375
    secrets: [docker_username, docker_password]
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD quay.io
      - docker push quay.io/skuid/keyman:${DRONE_REPO_BRANCH}-${DRONE_BUILD_NUMBER}
    when:
      branch: master
      event: push
