version: "3"
services:
  redis:
    image: redis:latest
    ports:
    - '6379'
  ssh:
    build:
      context: ./demo
    ports:
    - '2222:2222'
  keyman:
    build:
      context: ./
    ports:
    - '3000:3000'
    - '3001:3001'
    volumes:
    - './demo/:/demo/'
    environment:
      KEYMAN_KEY: "/demo/ca"
      KEYMAN_REDIS_HOST: redis
      KEYMAN_GROUPS: ""
      KEYMAN_DOMAIN: ""
      KEYMAN_ADMIN_USERNAME: ""
      KEYMAN_SERVICE_ACCOUNT: "/demo/sa.json" # Create this SA token
      KEYMAN_CLIENT_ID: ""
